name: Manual Echo

on:
  workflow_dispatch:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Copy script to EC2
        run: |
          # Copy the command file to EC2 instance
          scp -i ~/.ssh/id_rsa scripts/loader/dld_schema.sql ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/scripts
          scp -i ~/.ssh/id_rsa scripts/loader/load_csv.sh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/scripts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Set variables

            # Make the command file executable if it exists
            PGDATABASE=${{ secrets.PG_DATABASE }} PGHOST=${{ secrets.PG_HOST }} PGPORT=${{ secrets.PG_PORT }} PGUSER=${{ secrets.PG_USER }} PGPASSWORD=${{ secrets.PG_PASSWORD }} psql -f ~/scripts/loader/dld_schema.sql

            # Load data into database
            echo "Loading data into database..."
            PGDATABASE=${{ secrets.PG_DATABASE }} PGHOST=${{ secrets.PG_HOST }} PGPORT=${{ secrets.PG_PORT }} PGUSER=${{ secrets.PG_USER }} PGPASSWORD=${{ secrets.PG_PASSWORD }} ~/scripts/loader/load_csv.sh /opt/fractional/csv

          EOF
        
      - name: Cleanup SSH key
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa